/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const OrderId = IDL.Nat;
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const OrderStatus = IDL.Variant({
  'new' : IDL.Null,
  'completed' : IDL.Null,
  'ongoing' : IDL.Null,
  'rejected' : IDL.Null,
});
export const OrderInternal = IDL.Record({
  'id' : OrderId,
  'customerName' : IDL.Text,
  'status' : OrderStatus,
  'deliveryFee' : IDL.Float64,
  'customerPhone' : IDL.Text,
  'pickupAddress' : IDL.Text,
  'assignedDeliveryBoy' : IDL.Opt(IDL.Principal),
  'distanceKm' : IDL.Float64,
  'dropoffAddress' : IDL.Text,
  'createdTimestamp' : IDL.Int,
});
export const T = IDL.Record({
  'name' : IDL.Text,
  'isOnline' : IDL.Bool,
  'phoneNumber' : IDL.Text,
  'location' : IDL.Record({
    'latitude' : IDL.Float64,
    'longitude' : IDL.Float64,
  }),
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'isOnline' : IDL.Bool,
  'phoneNumber' : IDL.Text,
  'location' : IDL.Record({
    'latitude' : IDL.Float64,
    'longitude' : IDL.Float64,
  }),
});
export const Location = IDL.Record({
  'latitude' : IDL.Float64,
  'longitude' : IDL.Float64,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'acceptOrder' : IDL.Func([OrderId], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'completeOrder' : IDL.Func([OrderId], [], []),
  'createOrder' : IDL.Func([OrderInternal], [OrderId], []),
  'createSampleOrders' : IDL.Func([], [], []),
  'getAllDeliveryBoys' : IDL.Func([], [IDL.Vec(T)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDeliveryBoyEarnings' : IDL.Func(
      [IDL.Principal],
      [IDL.Float64],
      ['query'],
    ),
  'getDeliveryHistory' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(OrderInternal)],
      ['query'],
    ),
  'getOrder' : IDL.Func([OrderId], [OrderInternal], ['query']),
  'getOrdersByStatus' : IDL.Func(
      [OrderStatus],
      [IDL.Vec(OrderInternal)],
      ['query'],
    ),
  'getOrdersForDeliveryBoy' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(OrderInternal)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'rejectOrder' : IDL.Func([OrderId], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'searchOrdersByCustomerName' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(OrderInternal)],
      ['query'],
    ),
  'setDeliveryBoyOnlineStatus' : IDL.Func([IDL.Bool], [], []),
  'updateDeliveryBoyLocation' : IDL.Func([Location], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const OrderId = IDL.Nat;
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const OrderStatus = IDL.Variant({
    'new' : IDL.Null,
    'completed' : IDL.Null,
    'ongoing' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const OrderInternal = IDL.Record({
    'id' : OrderId,
    'customerName' : IDL.Text,
    'status' : OrderStatus,
    'deliveryFee' : IDL.Float64,
    'customerPhone' : IDL.Text,
    'pickupAddress' : IDL.Text,
    'assignedDeliveryBoy' : IDL.Opt(IDL.Principal),
    'distanceKm' : IDL.Float64,
    'dropoffAddress' : IDL.Text,
    'createdTimestamp' : IDL.Int,
  });
  const T = IDL.Record({
    'name' : IDL.Text,
    'isOnline' : IDL.Bool,
    'phoneNumber' : IDL.Text,
    'location' : IDL.Record({
      'latitude' : IDL.Float64,
      'longitude' : IDL.Float64,
    }),
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'isOnline' : IDL.Bool,
    'phoneNumber' : IDL.Text,
    'location' : IDL.Record({
      'latitude' : IDL.Float64,
      'longitude' : IDL.Float64,
    }),
  });
  const Location = IDL.Record({
    'latitude' : IDL.Float64,
    'longitude' : IDL.Float64,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'acceptOrder' : IDL.Func([OrderId], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'completeOrder' : IDL.Func([OrderId], [], []),
    'createOrder' : IDL.Func([OrderInternal], [OrderId], []),
    'createSampleOrders' : IDL.Func([], [], []),
    'getAllDeliveryBoys' : IDL.Func([], [IDL.Vec(T)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDeliveryBoyEarnings' : IDL.Func(
        [IDL.Principal],
        [IDL.Float64],
        ['query'],
      ),
    'getDeliveryHistory' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(OrderInternal)],
        ['query'],
      ),
    'getOrder' : IDL.Func([OrderId], [OrderInternal], ['query']),
    'getOrdersByStatus' : IDL.Func(
        [OrderStatus],
        [IDL.Vec(OrderInternal)],
        ['query'],
      ),
    'getOrdersForDeliveryBoy' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(OrderInternal)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'rejectOrder' : IDL.Func([OrderId], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'searchOrdersByCustomerName' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(OrderInternal)],
        ['query'],
      ),
    'setDeliveryBoyOnlineStatus' : IDL.Func([IDL.Bool], [], []),
    'updateDeliveryBoyLocation' : IDL.Func([Location], [], []),
  });
};

export const init = ({ IDL }) => { return []; };