/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Location { 'latitude' : number, 'longitude' : number }
export type OrderId = bigint;
export interface OrderInternal {
  'id' : OrderId,
  'customerName' : string,
  'status' : OrderStatus,
  'deliveryFee' : number,
  'customerPhone' : string,
  'pickupAddress' : string,
  'assignedDeliveryBoy' : [] | [Principal],
  'distanceKm' : number,
  'dropoffAddress' : string,
  'createdTimestamp' : bigint,
}
export type OrderStatus = { 'new' : null } |
  { 'completed' : null } |
  { 'ongoing' : null } |
  { 'rejected' : null };
export interface T {
  'name' : string,
  'isOnline' : boolean,
  'phoneNumber' : string,
  'location' : { 'latitude' : number, 'longitude' : number },
}
export interface UserProfile {
  'name' : string,
  'isOnline' : boolean,
  'phoneNumber' : string,
  'location' : { 'latitude' : number, 'longitude' : number },
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'acceptOrder' : ActorMethod<[OrderId], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'completeOrder' : ActorMethod<[OrderId], undefined>,
  'createOrder' : ActorMethod<[OrderInternal], OrderId>,
  'createSampleOrders' : ActorMethod<[], undefined>,
  'getAllDeliveryBoys' : ActorMethod<[], Array<T>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getDeliveryBoyEarnings' : ActorMethod<[Principal], number>,
  'getDeliveryHistory' : ActorMethod<[Principal], Array<OrderInternal>>,
  'getOrder' : ActorMethod<[OrderId], OrderInternal>,
  'getOrdersByStatus' : ActorMethod<[OrderStatus], Array<OrderInternal>>,
  'getOrdersForDeliveryBoy' : ActorMethod<[Principal], Array<OrderInternal>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'rejectOrder' : ActorMethod<[OrderId], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'searchOrdersByCustomerName' : ActorMethod<[string], Array<OrderInternal>>,
  'setDeliveryBoyOnlineStatus' : ActorMethod<[boolean], undefined>,
  'updateDeliveryBoyLocation' : ActorMethod<[Location], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];