/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Location {
    latitude: number;
    longitude: number;
}
export interface OrderInternal {
    id: OrderId;
    customerName: string;
    status: OrderStatus;
    deliveryFee: number;
    customerPhone: string;
    pickupAddress: string;
    assignedDeliveryBoy?: Principal;
    distanceKm: number;
    dropoffAddress: string;
    createdTimestamp: bigint;
}
export interface T {
    name: string;
    isOnline: boolean;
    phoneNumber: string;
    location: {
        latitude: number;
        longitude: number;
    };
}
export interface UserProfile {
    name: string;
    isOnline: boolean;
    phoneNumber: string;
    location: {
        latitude: number;
        longitude: number;
    };
}
export type OrderId = bigint;
export enum OrderStatus {
    new_ = "new",
    completed = "completed",
    ongoing = "ongoing",
    rejected = "rejected"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    acceptOrder(orderId: OrderId): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    completeOrder(orderId: OrderId): Promise<void>;
    createOrder(order: OrderInternal): Promise<OrderId>;
    createSampleOrders(): Promise<void>;
    getAllDeliveryBoys(): Promise<Array<T>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getDeliveryBoyEarnings(deliveryBoy: Principal): Promise<number>;
    getDeliveryHistory(deliveryBoy: Principal): Promise<Array<OrderInternal>>;
    getOrder(orderId: OrderId): Promise<OrderInternal>;
    getOrdersByStatus(status: OrderStatus): Promise<Array<OrderInternal>>;
    getOrdersForDeliveryBoy(deliveryBoy: Principal): Promise<Array<OrderInternal>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    rejectOrder(orderId: OrderId): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    searchOrdersByCustomerName(searchTerm: string): Promise<Array<OrderInternal>>;
    setDeliveryBoyOnlineStatus(isOnline: boolean): Promise<void>;
    updateDeliveryBoyLocation(location: Location): Promise<void>;
}
import type { OrderId as _OrderId, OrderInternal as _OrderInternal, OrderStatus as _OrderStatus, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async acceptOrder(arg0: OrderId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.acceptOrder(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.acceptOrder(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async completeOrder(arg0: OrderId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.completeOrder(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.completeOrder(arg0);
            return result;
        }
    }
    async createOrder(arg0: OrderInternal): Promise<OrderId> {
        if (this.processError) {
            try {
                const result = await this.actor.createOrder(to_candid_OrderInternal_n3(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createOrder(to_candid_OrderInternal_n3(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async createSampleOrders(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createSampleOrders();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createSampleOrders();
            return result;
        }
    }
    async getAllDeliveryBoys(): Promise<Array<T>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllDeliveryBoys();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllDeliveryBoys();
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDeliveryBoyEarnings(arg0: Principal): Promise<number> {
        if (this.processError) {
            try {
                const result = await this.actor.getDeliveryBoyEarnings(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDeliveryBoyEarnings(arg0);
            return result;
        }
    }
    async getDeliveryHistory(arg0: Principal): Promise<Array<OrderInternal>> {
        if (this.processError) {
            try {
                const result = await this.actor.getDeliveryHistory(arg0);
                return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDeliveryHistory(arg0);
            return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getOrder(arg0: OrderId): Promise<OrderInternal> {
        if (this.processError) {
            try {
                const result = await this.actor.getOrder(arg0);
                return from_candid_OrderInternal_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOrder(arg0);
            return from_candid_OrderInternal_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getOrdersByStatus(arg0: OrderStatus): Promise<Array<OrderInternal>> {
        if (this.processError) {
            try {
                const result = await this.actor.getOrdersByStatus(to_candid_OrderStatus_n5(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOrdersByStatus(to_candid_OrderStatus_n5(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getOrdersForDeliveryBoy(arg0: Principal): Promise<Array<OrderInternal>> {
        if (this.processError) {
            try {
                const result = await this.actor.getOrdersForDeliveryBoy(arg0);
                return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOrdersForDeliveryBoy(arg0);
            return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async rejectOrder(arg0: OrderId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.rejectOrder(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.rejectOrder(arg0);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async searchOrdersByCustomerName(arg0: string): Promise<Array<OrderInternal>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchOrdersByCustomerName(arg0);
                return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchOrdersByCustomerName(arg0);
            return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async setDeliveryBoyOnlineStatus(arg0: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setDeliveryBoyOnlineStatus(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setDeliveryBoyOnlineStatus(arg0);
            return result;
        }
    }
    async updateDeliveryBoyLocation(arg0: Location): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateDeliveryBoyLocation(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateDeliveryBoyLocation(arg0);
            return result;
        }
    }
}
function from_candid_OrderInternal_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _OrderInternal): OrderInternal {
    return from_candid_record_n12(_uploadFile, _downloadFile, value);
}
function from_candid_OrderStatus_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _OrderStatus): OrderStatus {
    return from_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [Principal]): Principal | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _OrderId;
    customerName: string;
    status: _OrderStatus;
    deliveryFee: number;
    customerPhone: string;
    pickupAddress: string;
    assignedDeliveryBoy: [] | [Principal];
    distanceKm: number;
    dropoffAddress: string;
    createdTimestamp: bigint;
}): {
    id: OrderId;
    customerName: string;
    status: OrderStatus;
    deliveryFee: number;
    customerPhone: string;
    pickupAddress: string;
    assignedDeliveryBoy?: Principal;
    distanceKm: number;
    dropoffAddress: string;
    createdTimestamp: bigint;
} {
    return {
        id: value.id,
        customerName: value.customerName,
        status: from_candid_OrderStatus_n13(_uploadFile, _downloadFile, value.status),
        deliveryFee: value.deliveryFee,
        customerPhone: value.customerPhone,
        pickupAddress: value.pickupAddress,
        assignedDeliveryBoy: record_opt_to_undefined(from_candid_opt_n15(_uploadFile, _downloadFile, value.assignedDeliveryBoy)),
        distanceKm: value.distanceKm,
        dropoffAddress: value.dropoffAddress,
        createdTimestamp: value.createdTimestamp
    };
}
function from_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    new: null;
} | {
    completed: null;
} | {
    ongoing: null;
} | {
    rejected: null;
}): OrderStatus {
    return "new" in value ? OrderStatus.new : "completed" in value ? OrderStatus.completed : "ongoing" in value ? OrderStatus.ongoing : "rejected" in value ? OrderStatus.rejected : value;
}
function from_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_OrderInternal>): Array<OrderInternal> {
    return value.map((x)=>from_candid_OrderInternal_n11(_uploadFile, _downloadFile, x));
}
function to_candid_OrderInternal_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: OrderInternal): _OrderInternal {
    return to_candid_record_n4(_uploadFile, _downloadFile, value);
}
function to_candid_OrderStatus_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: OrderStatus): _OrderStatus {
    return to_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_record_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: OrderId;
    customerName: string;
    status: OrderStatus;
    deliveryFee: number;
    customerPhone: string;
    pickupAddress: string;
    assignedDeliveryBoy?: Principal;
    distanceKm: number;
    dropoffAddress: string;
    createdTimestamp: bigint;
}): {
    id: _OrderId;
    customerName: string;
    status: _OrderStatus;
    deliveryFee: number;
    customerPhone: string;
    pickupAddress: string;
    assignedDeliveryBoy: [] | [Principal];
    distanceKm: number;
    dropoffAddress: string;
    createdTimestamp: bigint;
} {
    return {
        id: value.id,
        customerName: value.customerName,
        status: to_candid_OrderStatus_n5(_uploadFile, _downloadFile, value.status),
        deliveryFee: value.deliveryFee,
        customerPhone: value.customerPhone,
        pickupAddress: value.pickupAddress,
        assignedDeliveryBoy: value.assignedDeliveryBoy ? candid_some(value.assignedDeliveryBoy) : candid_none(),
        distanceKm: value.distanceKm,
        dropoffAddress: value.dropoffAddress,
        createdTimestamp: value.createdTimestamp
    };
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: OrderStatus): {
    new: null;
} | {
    completed: null;
} | {
    ongoing: null;
} | {
    rejected: null;
} {
    return value == OrderStatus.new ? {
        new_: null
    } : value == OrderStatus.completed ? {
        completed: null
    } : value == OrderStatus.ongoing ? {
        ongoing: null
    } : value == OrderStatus.rejected ? {
        rejected: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
